### ISSUE TITLE
/src/draggable.js#L24 不应该直接用 Regular

### ISSUE THREAD

**Issue by zyy7259** [regular-ui/ui-dragdrop#1]
应该在最上面声明`var Regular = require('regularjs');`

我是在使用 RequireJS 引入 RGUI 时出错了，发现这里写法不对

**Comment by z-ZYS-s** [comment]
谢谢，我看一看

**Comment by z-ZYS-s** [comment]
已修复
https://github.com/regular-ui/regular-ui/releases/tag/v0.1.6
